
package itmo.ws.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CatWebServiceImpl", targetNamespace = "http://impl.ws.itmo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CatWebServiceImpl {


    /**
     * 
     * @return
     *     returns java.util.List<itmo.ws.impl.Cat>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCats", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCats")
    @ResponseWrapper(localName = "getCatsResponse", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatsResponse")
    @Action(input = "http://impl.ws.itmo/CatWebServiceImpl/getCatsRequest", output = "http://impl.ws.itmo/CatWebServiceImpl/getCatsResponse")
    public List<Cat> getCats();

    /**
     * 
     * @param name
     * @return
     *     returns java.util.List<itmo.ws.impl.Cat>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCatsByName", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatsByName")
    @ResponseWrapper(localName = "getCatsByNameResponse", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatsByNameResponse")
    @Action(input = "http://impl.ws.itmo/CatWebServiceImpl/getCatsByNameRequest", output = "http://impl.ws.itmo/CatWebServiceImpl/getCatsByNameResponse")
    public List<Cat> getCatsByName(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param uid
     * @return
     *     returns itmo.ws.impl.Cat
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCatByUid", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatByUid")
    @ResponseWrapper(localName = "getCatByUidResponse", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatByUidResponse")
    @Action(input = "http://impl.ws.itmo/CatWebServiceImpl/getCatByUidRequest", output = "http://impl.ws.itmo/CatWebServiceImpl/getCatByUidResponse")
    public Cat getCatByUid(
        @WebParam(name = "uid", targetNamespace = "")
        int uid);

    /**
     * 
     * @param eyesColor
     * @param furColor
     * @return
     *     returns java.util.List<itmo.ws.impl.Cat>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCatsByDescription", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatsByDescription")
    @ResponseWrapper(localName = "getCatsByDescriptionResponse", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatsByDescriptionResponse")
    @Action(input = "http://impl.ws.itmo/CatWebServiceImpl/getCatsByDescriptionRequest", output = "http://impl.ws.itmo/CatWebServiceImpl/getCatsByDescriptionResponse")
    public List<Cat> getCatsByDescription(
        @WebParam(name = "eyesColor", targetNamespace = "")
        String eyesColor,
        @WebParam(name = "furColor", targetNamespace = "")
        String furColor);

    /**
     * 
     * @param breed
     * @return
     *     returns java.util.List<itmo.ws.impl.Cat>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCatsByBreed", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatsByBreed")
    @ResponseWrapper(localName = "getCatsByBreedResponse", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatsByBreedResponse")
    @Action(input = "http://impl.ws.itmo/CatWebServiceImpl/getCatsByBreedRequest", output = "http://impl.ws.itmo/CatWebServiceImpl/getCatsByBreedResponse")
    public List<Cat> getCatsByBreed(
        @WebParam(name = "breed", targetNamespace = "")
        String breed);

    /**
     * 
     * @param owner
     * @return
     *     returns java.util.List<itmo.ws.impl.Cat>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCatsByOwner", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatsByOwner")
    @ResponseWrapper(localName = "getCatsByOwnerResponse", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatsByOwnerResponse")
    @Action(input = "http://impl.ws.itmo/CatWebServiceImpl/getCatsByOwnerRequest", output = "http://impl.ws.itmo/CatWebServiceImpl/getCatsByOwnerResponse")
    public List<Cat> getCatsByOwner(
        @WebParam(name = "owner", targetNamespace = "")
        String owner);

    /**
     * 
     * @param owner
     * @param name
     * @return
     *     returns java.util.List<itmo.ws.impl.Cat>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCatsByOwnerAndName", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatsByOwnerAndName")
    @ResponseWrapper(localName = "getCatsByOwnerAndNameResponse", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatsByOwnerAndNameResponse")
    @Action(input = "http://impl.ws.itmo/CatWebServiceImpl/getCatsByOwnerAndNameRequest", output = "http://impl.ws.itmo/CatWebServiceImpl/getCatsByOwnerAndNameResponse")
    public List<Cat> getCatsByOwnerAndName(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "owner", targetNamespace = "")
        String owner);

    /**
     * 
     * @param name
     * @param age
     * @return
     *     returns java.util.List<itmo.ws.impl.Cat>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCatsByNameAndAge", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatsByNameAndAge")
    @ResponseWrapper(localName = "getCatsByNameAndAgeResponse", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatsByNameAndAgeResponse")
    @Action(input = "http://impl.ws.itmo/CatWebServiceImpl/getCatsByNameAndAgeRequest", output = "http://impl.ws.itmo/CatWebServiceImpl/getCatsByNameAndAgeResponse")
    public List<Cat> getCatsByNameAndAge(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "age", targetNamespace = "")
        int age);

    /**
     * 
     * @param owner
     * @param breed
     * @return
     *     returns java.util.List<itmo.ws.impl.Cat>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCatsByBreedAndOwner", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatsByBreedAndOwner")
    @ResponseWrapper(localName = "getCatsByBreedAndOwnerResponse", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatsByBreedAndOwnerResponse")
    @Action(input = "http://impl.ws.itmo/CatWebServiceImpl/getCatsByBreedAndOwnerRequest", output = "http://impl.ws.itmo/CatWebServiceImpl/getCatsByBreedAndOwnerResponse")
    public List<Cat> getCatsByBreedAndOwner(
        @WebParam(name = "breed", targetNamespace = "")
        String breed,
        @WebParam(name = "owner", targetNamespace = "")
        String owner);

    /**
     * 
     * @param eyesColor
     * @param furColor
     * @param breed
     * @return
     *     returns java.util.List<itmo.ws.impl.Cat>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCatsByFullDescription", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatsByFullDescription")
    @ResponseWrapper(localName = "getCatsByFullDescriptionResponse", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatsByFullDescriptionResponse")
    @Action(input = "http://impl.ws.itmo/CatWebServiceImpl/getCatsByFullDescriptionRequest", output = "http://impl.ws.itmo/CatWebServiceImpl/getCatsByFullDescriptionResponse")
    public List<Cat> getCatsByFullDescription(
        @WebParam(name = "eyesColor", targetNamespace = "")
        String eyesColor,
        @WebParam(name = "furColor", targetNamespace = "")
        String furColor,
        @WebParam(name = "breed", targetNamespace = "")
        String breed);

}
