
package itmo.ws.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CatWebServiceImpl", targetNamespace = "http://impl.ws.itmo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CatWebServiceImpl {


    /**
     * 
     * @return
     *     returns java.util.List<itmo.ws.impl.Cat>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCats", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCats")
    @ResponseWrapper(localName = "getCatsResponse", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatsResponse")
    @Action(input = "http://impl.ws.itmo/CatWebServiceImpl/getCatsRequest", output = "http://impl.ws.itmo/CatWebServiceImpl/getCatsResponse")
    public List<itmo.ws.impl.Cat> getCats();

    /**
     * 
     * @param name
     * @return
     *     returns java.util.List<itmo.ws.impl.Cat>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCatsByName", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatsByName")
    @ResponseWrapper(localName = "getCatsByNameResponse", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatsByNameResponse")
    @Action(input = "http://impl.ws.itmo/CatWebServiceImpl/getCatsByNameRequest", output = "http://impl.ws.itmo/CatWebServiceImpl/getCatsByNameResponse")
    public List<itmo.ws.impl.Cat> getCatsByName(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param uid
     * @return
     *     returns itmo.ws.impl.Cat
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCatByUid", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatByUid")
    @ResponseWrapper(localName = "getCatByUidResponse", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatByUidResponse")
    @Action(input = "http://impl.ws.itmo/CatWebServiceImpl/getCatByUidRequest", output = "http://impl.ws.itmo/CatWebServiceImpl/getCatByUidResponse")
    public itmo.ws.impl.Cat getCatByUid(
        @WebParam(name = "uid", targetNamespace = "")
        int uid);

    /**
     * 
     * @param eyesColor
     * @param furColor
     * @return
     *     returns java.util.List<itmo.ws.impl.Cat>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCatsByDescription", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatsByDescription")
    @ResponseWrapper(localName = "getCatsByDescriptionResponse", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatsByDescriptionResponse")
    @Action(input = "http://impl.ws.itmo/CatWebServiceImpl/getCatsByDescriptionRequest", output = "http://impl.ws.itmo/CatWebServiceImpl/getCatsByDescriptionResponse")
    public List<itmo.ws.impl.Cat> getCatsByDescription(
        @WebParam(name = "eyesColor", targetNamespace = "")
        String eyesColor,
        @WebParam(name = "furColor", targetNamespace = "")
        String furColor);

    /**
     * 
     * @param breed
     * @return
     *     returns java.util.List<itmo.ws.impl.Cat>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCatsByBreed", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatsByBreed")
    @ResponseWrapper(localName = "getCatsByBreedResponse", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatsByBreedResponse")
    @Action(input = "http://impl.ws.itmo/CatWebServiceImpl/getCatsByBreedRequest", output = "http://impl.ws.itmo/CatWebServiceImpl/getCatsByBreedResponse")
    public List<itmo.ws.impl.Cat> getCatsByBreed(
        @WebParam(name = "breed", targetNamespace = "")
        String breed);

    /**
     * 
     * @param owner
     * @return
     *     returns java.util.List<itmo.ws.impl.Cat>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCatsByOwner", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatsByOwner")
    @ResponseWrapper(localName = "getCatsByOwnerResponse", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatsByOwnerResponse")
    @Action(input = "http://impl.ws.itmo/CatWebServiceImpl/getCatsByOwnerRequest", output = "http://impl.ws.itmo/CatWebServiceImpl/getCatsByOwnerResponse")
    public List<itmo.ws.impl.Cat> getCatsByOwner(
        @WebParam(name = "owner", targetNamespace = "")
        String owner);

    /**
     * 
     * @param owner
     * @param name
     * @return
     *     returns java.util.List<itmo.ws.impl.Cat>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCatsByOwnerAndName", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatsByOwnerAndName")
    @ResponseWrapper(localName = "getCatsByOwnerAndNameResponse", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatsByOwnerAndNameResponse")
    @Action(input = "http://impl.ws.itmo/CatWebServiceImpl/getCatsByOwnerAndNameRequest", output = "http://impl.ws.itmo/CatWebServiceImpl/getCatsByOwnerAndNameResponse")
    public List<itmo.ws.impl.Cat> getCatsByOwnerAndName(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "owner", targetNamespace = "")
        String owner);

    /**
     * 
     * @param name
     * @param age
     * @return
     *     returns java.util.List<itmo.ws.impl.Cat>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCatsByNameAndAge", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatsByNameAndAge")
    @ResponseWrapper(localName = "getCatsByNameAndAgeResponse", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatsByNameAndAgeResponse")
    @Action(input = "http://impl.ws.itmo/CatWebServiceImpl/getCatsByNameAndAgeRequest", output = "http://impl.ws.itmo/CatWebServiceImpl/getCatsByNameAndAgeResponse")
    public List<itmo.ws.impl.Cat> getCatsByNameAndAge(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "age", targetNamespace = "")
        int age);

    /**
     * 
     * @param owner
     * @param breed
     * @return
     *     returns java.util.List<itmo.ws.impl.Cat>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCatsByBreedAndOwner", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatsByBreedAndOwner")
    @ResponseWrapper(localName = "getCatsByBreedAndOwnerResponse", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatsByBreedAndOwnerResponse")
    @Action(input = "http://impl.ws.itmo/CatWebServiceImpl/getCatsByBreedAndOwnerRequest", output = "http://impl.ws.itmo/CatWebServiceImpl/getCatsByBreedAndOwnerResponse")
    public List<itmo.ws.impl.Cat> getCatsByBreedAndOwner(
        @WebParam(name = "breed", targetNamespace = "")
        String breed,
        @WebParam(name = "owner", targetNamespace = "")
        String owner);

    /**
     * 
     * @param eyesColor
     * @param furColor
     * @param breed
     * @return
     *     returns java.util.List<itmo.ws.impl.Cat>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCatsByFullDescription", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatsByFullDescription")
    @ResponseWrapper(localName = "getCatsByFullDescriptionResponse", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetCatsByFullDescriptionResponse")
    @Action(input = "http://impl.ws.itmo/CatWebServiceImpl/getCatsByFullDescriptionRequest", output = "http://impl.ws.itmo/CatWebServiceImpl/getCatsByFullDescriptionResponse")
    public List<Cat> getCatsByFullDescription(
        @WebParam(name = "eyesColor", targetNamespace = "")
        String eyesColor,
        @WebParam(name = "furColor", targetNamespace = "")
        String furColor,
        @WebParam(name = "breed", targetNamespace = "")
        String breed);

    /**
     * 
     * @param ownerName
     * @param eyesColor
     * @param name
     * @param furColor
     * @param age
     * @param breed
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createCat", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.CreateCat")
    @ResponseWrapper(localName = "createCatResponse", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.CreateCatResponse")
    @Action(input = "http://impl.ws.itmo/CatWebServiceImpl/createCatRequest", output = "http://impl.ws.itmo/CatWebServiceImpl/createCatResponse")
    public int createCat(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "age", targetNamespace = "")
        int age,
        @WebParam(name = "eyesColor", targetNamespace = "")
        String eyesColor,
        @WebParam(name = "furColor", targetNamespace = "")
        String furColor,
        @WebParam(name = "breed", targetNamespace = "")
        String breed,
        @WebParam(name = "ownerName", targetNamespace = "")
        String ownerName);

    /**
     * 
     * @param uid
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteCat", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.DeleteCat")
    @ResponseWrapper(localName = "deleteCatResponse", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.DeleteCatResponse")
    @Action(input = "http://impl.ws.itmo/CatWebServiceImpl/deleteCatRequest", output = "http://impl.ws.itmo/CatWebServiceImpl/deleteCatResponse")
    public boolean deleteCat(
        @WebParam(name = "uid", targetNamespace = "")
        int uid);

    /**
     * 
     * @param uid
     * @param name
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateCatName", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.UpdateCatName")
    @ResponseWrapper(localName = "updateCatNameResponse", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.UpdateCatNameResponse")
    @Action(input = "http://impl.ws.itmo/CatWebServiceImpl/updateCatNameRequest", output = "http://impl.ws.itmo/CatWebServiceImpl/updateCatNameResponse")
    public boolean updateCatName(
        @WebParam(name = "uid", targetNamespace = "")
        int uid,
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param uid
     * @param eyesColor
     * @param furColor
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateCatDescription", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.UpdateCatDescription")
    @ResponseWrapper(localName = "updateCatDescriptionResponse", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.UpdateCatDescriptionResponse")
    @Action(input = "http://impl.ws.itmo/CatWebServiceImpl/updateCatDescriptionRequest", output = "http://impl.ws.itmo/CatWebServiceImpl/updateCatDescriptionResponse")
    public boolean updateCatDescription(
        @WebParam(name = "uid", targetNamespace = "")
        int uid,
        @WebParam(name = "eyesColor", targetNamespace = "")
        String eyesColor,
        @WebParam(name = "furColor", targetNamespace = "")
        String furColor);

    /**
     * 
     * @param uid
     * @param breed
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateCatBreed", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.UpdateCatBreed")
    @ResponseWrapper(localName = "updateCatBreedResponse", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.UpdateCatBreedResponse")
    @Action(input = "http://impl.ws.itmo/CatWebServiceImpl/updateCatBreedRequest", output = "http://impl.ws.itmo/CatWebServiceImpl/updateCatBreedResponse")
    public boolean updateCatBreed(
        @WebParam(name = "uid", targetNamespace = "")
        int uid,
        @WebParam(name = "breed", targetNamespace = "")
        String breed);

    /**
     * 
     * @param owner
     * @param uid
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateCatOwner", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.UpdateCatOwner")
    @ResponseWrapper(localName = "updateCatOwnerResponse", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.UpdateCatOwnerResponse")
    @Action(input = "http://impl.ws.itmo/CatWebServiceImpl/updateCatOwnerRequest", output = "http://impl.ws.itmo/CatWebServiceImpl/updateCatOwnerResponse")
    public boolean updateCatOwner(
        @WebParam(name = "uid", targetNamespace = "")
        int uid,
        @WebParam(name = "owner", targetNamespace = "")
        String owner);

    /**
     * 
     * @param uid
     * @param ownerName
     * @param eyesColor
     * @param name
     * @param furColor
     * @param age
     * @param breed
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateCat", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.UpdateCat")
    @ResponseWrapper(localName = "updateCatResponse", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.UpdateCatResponse")
    @Action(input = "http://impl.ws.itmo/CatWebServiceImpl/updateCatRequest", output = "http://impl.ws.itmo/CatWebServiceImpl/updateCatResponse")
    public boolean updateCat(
        @WebParam(name = "uid", targetNamespace = "")
        int uid,
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "age", targetNamespace = "")
        int age,
        @WebParam(name = "eyesColor", targetNamespace = "")
        String eyesColor,
        @WebParam(name = "furColor", targetNamespace = "")
        String furColor,
        @WebParam(name = "breed", targetNamespace = "")
        String breed,
        @WebParam(name = "ownerName", targetNamespace = "")
        String ownerName);

    /**
     * 
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFileAsAttachment", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetFileAsAttachment")
    @ResponseWrapper(localName = "getFileAsAttachmentResponse", targetNamespace = "http://impl.ws.itmo/", className = "itmo.ws.impl.GetFileAsAttachmentResponse")
    @Action(input = "http://impl.ws.itmo/CatWebServiceImpl/getFileAsAttachmentRequest", output = "http://impl.ws.itmo/CatWebServiceImpl/getFileAsAttachmentResponse")
    public byte[] getFileAsAttachment();

}
